# Assignment-1

Andres Salguero  - C0932873

Andrea Franco - C0931897

Vishv Patel - C0938107

Rajkumar Patel - C0934637

Harpreet kaur - C0936410

Gurpreet kaur - C0936411

Q1. You draw two cards from pack of 52 shuffled cards (without replacement). Create a Python Program to generate a Probability Distribution Table for getting zero to at most 2 ACES.

![Q1](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q1.jpeg?raw=true)

![Q1](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q1_1.jpg?raw=true)

![Q1](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q1_2.jpg?raw=true)

In [2]:
import pandas as pd
import numpy as np

# create factorial function
def factorial(n):
    if n == 0:
        return 1
    result= 1
    for i in range(1,n+1):
        result*=i
    return result

# create combination function
def comb(n,k):
    equation=factorial(n)//(factorial(k)*factorial(n-k))
    return equation 

# total number of cards is 52
total_cards = 52

# number of ace in deck
aces = 4

# non_aces in cards
non_aces= total_cards-aces

# total number of ways to draw 2 cards
total_methods= comb(total_cards,2)

# number of way to draw 0 ace
zero_ace= comb(non_aces,2)

# number of way to draw 1 ace
one_ace=comb(aces,1)*comb(non_aces,1)

# number of way to draw 2 ace
two_ace=comb(aces,2)

# probabilities
p_zero_ace= zero_ace/total_methods
p_one_ace= one_ace/total_methods
p_two_ace= two_ace/total_methods

# create probability distribution table 
data= {
    "Number of Aces":[0,1,2],
    "Number of Ways":[zero_ace,one_ace,two_ace],
    "Probability": [p_zero_ace,p_one_ace,p_two_ace]
}

prob_dis_table = pd.DataFrame(data)
prob_dis_table

Number of Aces  Number of Ways  Probability
0               0            1128     0.850679
1               1             192     0.144796
2               2               6     0.004525

Q2. Bag I contain 2 red and 8 black balls while another Bag II contains 5 red and 5 black balls. One ball is drawn at random from one of the bags, and it is found to be black. Create a Python Program to find the probability that it was drawn from Bag 2.

![Q1](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q2.jpeg?raw=true)

In [14]:
# defining the probability
pro_a = 0.5 # probability of bag 1
pro_b = 0.5 # probability of bag 2

pro_black_from_a = 0.8 # probability of getting black ball from bag 1
pro_black_from_b = 0.5 # probability of getting black ball from bag 2

# calculating total probability of getting black ball
pro_black = (pro_black_from_a * pro_b) + (pro_black_from_b * pro_a)

# calculating the probability that black ball was drawn from bag 2
pro_a_from_black = (pro_black_from_a * pro_b) / pro_black

# printing the result
print("probability of black_ball that drawn from bag 2 is :", pro_a_from_black )

probability of black_ball that drawn from bag 2 is : 0.6153846153846154


Q3. There are 3 red and 7 black balls in a bag. You are asked to draw 3 balls at random (with replacement) in three different trials. Create a Python program to find the probability of getting two red balls and one black ball? 



![Q3](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q3.jpeg?raw=true)


In [6]:
# total ball
total_balls = 10

# probality of red balls
p_red_balls = 3/total_balls

# probability of black balls
p_black_balls = 7/total_balls

# number trials provided
trials = 3

# calculating binomial as the number of trials are 3 and we there is replacement we need specific value
def binomial(x,trials,p):
    return comb(trials,x)*(p**x)*((1-p)**(trials-x))

# calculating probability for getting 2 red and 1 black
p_2r_1b = binomial(2,trials,p_red_balls)*binomial(1,trials,p_black_balls)

# printing the results
print("Probability to get 2 red and 1 black ball is with replacement is", p_2r_1b)

Probability to get 2 red and 1 black ball is with replacement is 0.035721


Q4. A Customer Call center receives on average 3.5 calls every hour. Write a Python Program to find the probability that it will receive at most 4 calls every hour?

![Q4](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q4_1.jpg?raw=true)


![Q1](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q4_2.jpg?raw=true)

In [10]:
avgcalls = 3.5 # this are given in question

# defining Poisson distribution as there time interval
def poisson(k, lamda_rate):
    # using the formula in getting its value to variable
    poission_prob=(lamda_rate**k)*(2.71828**(-lamda_rate))/factorial(k)
    return poission_prob # return the value function

# initial value of variable to 0
p_4calls = 0

# use for t calculate the cumulative probability to get 4 calls every hour
for i in range(5):
    p_4calls += poisson(i,avgcalls)
    
print("Probability to get at most 4 calls every hour is", p_4calls)

Probability to get at most 4 calls every hour is 0.7254466612154337


Q5. The Student Services at Cestar College receive 2 phone calls per hour. Write a Python Program to find the probability that a phone call will come within the next hour.

![Q5](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q5.jpeg?raw=true)

In [11]:
calls_per_hour = 2

# Probability of no calls in the next hour (k = 0)
P_0_calls = poisson(k=0, lamda_rate=calls_per_hour)

# Probability of at least one call
P_at_least_1_call = 1 - P_0_calls

print(f"The probability that at least one phone call will come within the next hour is: {P_at_least_1_call:.4f}")


The probability that at least one phone call will come within the next hour is: 0.8647


Q6. Create a Python Program to generate the Eigen Value and Eigen Vector for the following Matrix (3x3 dimension) (4 Marks)
[8  5  3]
[5  6  5]
[9  7  4]

![Q6](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q6_1.jpg?raw=true)

![Q6](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q6_2.jpg?raw=true)

![Q6](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q6_3.jpg?raw=true)

![Q6](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q6_4.jpg?raw=true)

![Q6](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q6_5.jpg?raw=true)

![Q6](https://github.com/afscomercial/introduction-artificial-intelligence/blob/main/assets/q6_7.jpg?raw=true)

In [16]:
m = np.array([[8, 5, 3], 
             [5, 6, 5],
             [9, 7, 4]])

def eigen(m) -> None:
    print("Original matrix:\n", 
      m) 
  
    # finding eigenvalues and eigenvectors 
    eigenvalues, eigenvectors = np.linalg.eig(m) 
    
    # printing eigen values 
    print("Eigen values of the matrix:\n", 
        eigenvalues) 
    
    # printing eigen vectors 
    print("Right eigenvectors of the matrix:\n", 
        eigenvectors)

eigen(m)

Original matrix:
 [[8 5 3]
 [5 6 5]
 [9 7 4]]
Eigen values of the matrix:
 [16.9258042   1.74957549 -0.67537969]
Right eigenvectors of the matrix:
 [[-0.52409766 -0.60009754  0.11371532]
 [-0.54089356  0.79623451 -0.64876924]
 [-0.65784177 -0.0767694   0.75244089]]
